name: Verify SSH Secrets

on:
  push:
    branches:
      - main

jobs:
  test-secrets:
    runs-on: ubuntu-latest

    steps:
      # Tester la connexion SSH
      - name: Test SSH Connection
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: echo "SSH connection successful!"
